# Generated by Django 5.0.7 on 2024-07-24 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='proudcts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('protection_against_moisture', models.BooleanField(blank=True, default=False, null=True)),
                ('cable_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('complete_set', models.CharField(max_length=255)),
                ('microphone', models.BooleanField(blank=True, default=False)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment', models.CharField(blank=True, max_length=50, null=True)),
                ('end_conversation', models.BooleanField(blank=True, default=False)),
                ('connector', models.CharField(blank=True, max_length=255, null=True)),
                ('volume_control', models.BooleanField(blank=True, default=False)),
                ('fastening_type', models.CharField(blank=True, max_length=50, null=True)),
                ('headphone_type', models.CharField(blank=True, max_length=50, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=70, null=True)),
                ('frequency_range', models.CharField(blank=True, max_length=50, null=True)),
                ('sensitivity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='proudcts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category')),
            ],
        ),
    ]
