# Generated by Django 5.0.7 on 2024-07-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cases_rating_alter_headphones_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
