# Generated by Django 5.0.7 on 2024-08-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cases_slug_headphones_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
